cornertext: "*กรณีจัดส่งสินค้าไม่สำเร็จ"

itemcount:
  - indicator: "ชิ้น"
    color: "#ffff00"

wordlist:
  - word: "ส่งในนาม"
    color: "#ff0000"
  - word: "กทม"
  - word: "กรุงเทพ"
  - word: "กรุงเทพมหานคร"
  - word: "สินค้าเกินจำนวนที่สามารถแสดงบนหน้า\nโปรดใช้งานบนเว็บไซต"
    color: "#ff00ff"
    extend x: 10
    extend y: 10

imagelist:
  - location: "./images/ecopostspecial.jpg"
    x: 0
    y: 20
    width: 100
    height: 100